### ISSUE TITLE
RecyclerView setPadding does not apply to scrollbar

### ISSUE THREAD

**Issue by jahirfiquitiva** [timusus/RecyclerView-FastScroll#74] opened 2018-02-05 17:15 UTC
The FastScroller height is not calculated taking padding into account, so this makes the FastScroller height bigger than the actual RecyclerView height

**Comment by timusus** [comment] 2018-02-11 04:03
Duplicate of #6. Will reopen.

**Closed as completed by timusus** 2018-02-11 04:03 UTC
